[package]
name = "client"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "liserk-client"
path = "src/main.rs"
test = false
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
