version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11
    environment:
      RABBITMQ_DEFAULT_USER: rmq
      RABBITMQ_DEFAULT_PASS: pass
    restart: on-failure
    ports:
     - 4369:4369
     - 5671:5671
     - 5672:5672
     - 25672:25672
     - 15671:15671
     - 15672:15672
    networks:
        - liserk-db

  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data:rw
    networks:
      - liserk-db


  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: swann@wizards-technologies.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    networks:
      - liserk-db

  redis:
    container_name: redis
    image: redis:3-alpine
    ports:
        - 6379:6379
    networks:
      - liserk-db

  server:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile-server
    ports:
      - 3000:3000
    network_mode: host

  client:
    build:
      context: ./
      dockerfile: Dockerfile-client
    networks:
      - liserk-db

networks:
  liserk-db:

volumes:
  database: {}
