version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER={user}
      - POSTGRES_PASSWORD={password}
    ports:
      - {port}:5432
    volumes:
      - data/{db_id}:/var/lib/postgresql/data
